#!/bin/python3

import math
import os
import random
import re
import sys


n = int(input())
arr = list(map(int, input().rstrip().split()))
rev_arr= []
for i in range(n):
    rev_arr.append(arr[n-i-1])

op_string=''
for i in range(len(rev_arr)):
    op_string +=str(rev_arr[i])+ ' '
    
print(op_string)
