#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    def getName(firstName,emailID):
        z=re.search("@\w*.\w*",emailID)
        if (z[0]=="@gmail.com"):
            return True
        else:
            return False
        
    N = int(input())
    res=[]

    for N_itr in range(N):
        firstNameEmailID = input().split()

        firstName = firstNameEmailID[0]

        emailID = firstNameEmailID[1]
        
        if(getName(firstName,emailID)):
            res.append(firstName)
            
    res.sort()
    for i in range(len(res)):
        print(res[i])
